

spring:
  application:
    name: ddd-spring-boot-demo

  # Thymeleaf configuration - FIXED
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

  # Static resources - ENHANCED
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
      cache:
        period: 0  # Disable cache for development

  # Database configuration
  datasource:
    url: jdbc:mysql://localhost:33016/demospringdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: efe5616f4273f9
    password: 39b498969aa7c5
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    user:
      password: root
      name: root
      roles:
        - USER
        - ADMIN
  mvc:
    static-path-pattern: /**

logging:
  level:
    org.springframework.security: debug
    org.springframework.web: debug  # Added for debugging static resources
server:
  port: 2222