spring:
  application:
    name: ddd-spring-boot-dem

    # Thymeleaf configuration
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

  #Static resources
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true

  #Database configuration
  datasource:
      url: jdbc:mysql://localhost:33016/demospringdb
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update # convenient in Dev environment
    properties:
      hibernate:
        format_sql: true
        user_sql_comments: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: efe5616f4273f9
    password: 39b498969aa7c5
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    user:
      password: root
      name: root
      roles: # multiple roles
        - USER
        - ADMIN
logging:
  level:
    org.springframework.security: debug
